#!/usr/bin/env python3
"""
gen_cdt.py -- Emit the CDT tables needed by the Rust signer.

Writes `src/cdt.rs`, which contains one `pub static` per CDT used by
any of the four parameter sets:

    CDT_SIGMA_0_TEST
    CDT_SIGMA_0_PRIME_TEST
    CDT_SIGMA_A_TEST
    CDT_SIGMA_B_TEST
    CDT_SIGMA_A_BENCH_4OF32
    CDT_SIGMA_A_BENCH
    CDT_SIGMA_A_PRODUCTION
    CDT_SIGMA_B_BENCH_PRODUCTION  (BENCH_4OF32 / BENCH / PRODUCTION share sigma_b)

At `BENCH_4OF32` / `BENCH_PARAMS` / `PRODUCTION_PARAMS`, `sigma_0` and
`sigma_0_prime` are large enough to trigger the FACCT-style sampler —
no CDT is shipped for those widths.

Usage
-----
    python scripts/gen_cdt.py > src/cdt.rs
"""

import math
import os
import sys
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
LOTRS_PY = os.path.normpath(os.path.join(HERE, "..", "..", "lotrs-py"))
if LOTRS_PY not in sys.path:
    sys.path.insert(0, LOTRS_PY)

from params import (                                              # noqa
    TEST_PARAMS, BENCH_PARAMS, BENCH_4OF32, PRODUCTION_PARAMS,
)
from sample import build_cdt, needs_large_gaussian_sampler       # noqa


U128_MAX = (1 << 128) - 1


def format_entries(cdt, indent="    ", per_line=4):
    """Format CDT entries as `0x...` u128 literals, wrapped.

    The Python reference clamps the last entry to 2^lam = 2^128, which
    is out of range for Rust's u128.  We clamp instead to `u128::MAX`:
    the binary search in `xof_sample_gaussian` converges to the last
    index for any `u` that would otherwise compare against the Python
    sentinel, so the sampled magnitude is unchanged.
    """
    lines = []
    for i in range(0, len(cdt), per_line):
        chunk = [min(v, U128_MAX) for v in cdt[i:i + per_line]]
        joined = ", ".join(f"0x{v:032x}" for v in chunk)
        lines.append(indent + joined + ",")
    return "\n".join(lines)


def emit_table(name, sigma, note=None):
    lam = 128
    cdt = build_cdt(sigma, lam=lam)
    entries = format_entries(cdt)
    comment = f"/// CDT for  sigma = {sigma:.6f},  lam = {lam},  len = {len(cdt)}."
    if note:
        comment += f"\n/// {note}"
    return (
        f"{comment}\n"
        f"pub static {name}: &[u128] = &[\n"
        f"{entries}\n"
        f"];\n"
    )


HEADER = textwrap.dedent('''\
    // Generated by scripts/gen_cdt.py — do not edit by hand.
    //
    // Cumulative distribution tables for every small-sigma Gaussian
    // width used by the LoTRS signer across TEST, BENCH, and
    // PRODUCTION parameter sets.  The large-sigma widths
    // (sigma_0 / sigma_0_prime at BENCH / PRODUCTION) are sampled via
    // the FACCT-style path in `sample.rs` rather than a table.
    //
    // Each entry is  cdt[k] = floor(Pr[|X| <= k] * 2^lam)  as in
    // `lotrs-py/sample.py::build_cdt`, with the last entry clamped to
    // `u128::MAX` (the Python side uses `2^128`; the sampler's binary
    // search converges to the same index either way).

    #![allow(dead_code)]
    #![allow(clippy::unreadable_literal)]

''')


def main():
    # Figure out which (param_set, which) pairs actually need a CDT.
    # Everything at TEST uses CDT; at BENCH / PRODUCTION, sigma_0 /
    # sigma_0_prime use FACCT, sigma_a / sigma_b use CDT.
    bench_sigma_b = BENCH_PARAMS.sigma_b
    prod_sigma_b = PRODUCTION_PARAMS.sigma_b
    assert abs(bench_sigma_b - prod_sigma_b) < 1e-9, \
        "BENCH and PRODUCTION sigma_b differ — can no longer share a table"

    # BENCH_PARAMS and BENCH_4OF32 share sigma_b (phi_b is fixed across T),
    # so no extra sigma_b table is needed for the T=4 variant.
    assert abs(BENCH_PARAMS.sigma_b - BENCH_4OF32.sigma_b) < 1e-9
    sections = [
        emit_table("CDT_SIGMA_0_TEST",        TEST_PARAMS.sigma_0),
        emit_table("CDT_SIGMA_0_PRIME_TEST",  TEST_PARAMS.sigma_0_prime),
        emit_table("CDT_SIGMA_A_TEST",        TEST_PARAMS.sigma_a),
        emit_table("CDT_SIGMA_B_TEST",        TEST_PARAMS.sigma_b),
        emit_table("CDT_SIGMA_A_BENCH_4OF32", BENCH_4OF32.sigma_a),
        emit_table("CDT_SIGMA_A_BENCH",       BENCH_PARAMS.sigma_a),
        emit_table("CDT_SIGMA_A_PRODUCTION",  PRODUCTION_PARAMS.sigma_a),
        emit_table("CDT_SIGMA_B_BENCH_PRODUCTION",
                   BENCH_PARAMS.sigma_b,
                   note="(BENCH variants and PRODUCTION share sigma_b = "
                        f"{BENCH_PARAMS.sigma_b:.3f})"),
    ]
    # Sanity: refuse to proceed if any of the *large* sigmas accidentally
    # becomes CDT-feasible — that would flip the Python dispatch rule,
    # and we'd silently miss a Rust-side mismatch.
    for par in (BENCH_4OF32, BENCH_PARAMS, PRODUCTION_PARAMS):
        assert needs_large_gaussian_sampler(par.sigma_0), \
            f"{par.name}: sigma_0 is no longer a FACCT case"
        assert needs_large_gaussian_sampler(par.sigma_0_prime), \
            f"{par.name}: sigma_0_prime is no longer a FACCT case"

    print(HEADER + "\n".join(sections))


if __name__ == "__main__":
    main()
